ig_list = [
    {
        "username": "@instagram",
        "owner": "Instagram",
        "followers": 552,
        "prof_act": "Social media platform",
    },
    {
        "username": "@cristiano",
        "owner": "Cristiano Ronaldo",
        "followers": 484,
        "prof_act": "Footballer",
    },
    {
        "username": "@kyliejenner",
        "owner": "Kylie Jenner",
        "followers": 370,
        "prof_act": "Television personality, model and businesswoman",
    },
    {
        "username": "@leomessi",
        "owner": "Lionel Messi",
        "followers": 363,
        "prof_act": "Footballer",
    },
    {
        "username": "@selenagomez",
        "owner": "Selena Gomez",
        "followers": 348,
        "prof_act": "Musician, actress, and businesswoman",
    },
    {
        "username": "@therock",
        "owner": "Dwayne Johnson",
        "followers": 339,
        "prof_act": "Actor and professional wrestler",
    },
    {
        "username": "@arianagrande",
        "owner": "Ariana Grande",
        "followers": 332,
        "prof_act": "Musician, actress and businesswoman",
    },
    {
        "username": "@kimkardashian",
        "owner": "Kim Kardashian",
        "followers": 330,
        "prof_act": "Television personality, model and businesswoman",
    },
    {
        "username": "@beyonce",
        "owner": "Beyoncé",
        "followers": 276,
        "prof_act": "Musician, actress and businesswoman",
    },
    {
        "username": "@khloekardashian",
        "owner": "Khloé Kardashian",
        "followers": 273,
        "prof_act": "Television personality and model",
    },
    {
        "username": "@justinbieber",
        "owner": "Justin Bieber",
        "followers": 259,
        "prof_act": "Musician",
    },
    {
        "username": "@kendalljenner",
        "owner": "Kendall Jenner",
        "followers": 258,
        "prof_act": "Model and television personality",
    },
    {
        "username": "@natgeo",
        "owner": "National Geographic",
        "followers": 240,
        "prof_act": "Magazine",
    },
    {
        "username": "@nike",
        "owner": "Nike",
        "followers": 239,
        "prof_act": "Sportswear multinational",
    },
    {
        "username": "@taylorswift",
        "owner": "Taylor Swift",
        "followers": 225,
        "prof_act": "Musician and actress",
    },
    {
        "username": "@jlo",
        "owner": "Jennifer Lopez",
        "followers": 223,
        "prof_act": "Musician and actress",
    },
    {
        "username": "@virat.kohli",
        "owner": "Virat Kohli",
        "followers": 215,
        "prof_act": "Cricketer",
    },
    {
        "username": "@nickiminaj",
        "owner": "Nicki Minaj",
        "followers": 202,
        "prof_act": "Musician",
    },
    {
        "username": "@kourtneykardash",
        "owner": "Kourtney Kardashian",
        "followers": 199,
        "prof_act": "Television personality and model",
    },
    {
        "username": "@mileycyrus",
        "owner": "Miley Cyrus",
        "followers": 183,
        "prof_act": "Musician and actress",
    },
    {
        "username": "@neymarjr",
        "owner": "Neymar",
        "followers": 179,
        "prof_act": "Footballer",
    },
    {
        "username": "@katyperry",
        "owner": "Katy Perry",
        "followers": 173,
        "prof_act": "Musician",
    },
    {
        "username": "@kevinhart4real",
        "owner": "Kevin Hart",
        "followers": 154,
        "prof_act": "Comedian and actor",
    },
    {
        "username": "@zendaya",
        "owner": "Zendaya",
        "followers": 152,
        "prof_act": "Actress and singer",
    },
    {
        "username": "@iamcardib",
        "owner": "Cardi B",
        "followers": 141,
        "prof_act": "Musician and actor",
    },
    {
        "username": "@ddlovato",
        "owner": "Demi Lovato",
        "followers": 140,
        "prof_act": "Musician and actor",
    },
    {
        "username": "@badgalriri",
        "owner": "Rihanna",
        "followers": 136,
        "prof_act": "Musician and businesswoman",
    },
    {
        "username": "@kingjames",
        "owner": "LeBron James",
        "followers": 133,
        "prof_act": "Basketball player",
    },
    {
        "username": "@theellenshow",
        "owner": "Ellen DeGeneres",
        "followers": 125,
        "prof_act": "Comedian and television personality",
    },
    {
        "username": "@realmadrid",
        "owner": "Real Madrid CF",
        "followers": 125,
        "prof_act": "Football club",
    },
    {
        "username": "@champagnepapi",
        "owner": "Drake",
        "followers": 121,
        "prof_act": "Musician",
    },
    {
        "username": "@chrisbrownofficial",
        "owner": "Chris Brown",
        "followers": 121,
        "prof_act": "Musician",
    },
    {
        "username": "@fcbarcelona",
        "owner": "FC Barcelona",
        "followers": 112,
        "prof_act": "Football club",
    },
    {
        "username": "@billieeilish",
        "owner": "Billie Eilish",
        "followers": 106,
        "prof_act": "Musician",
    },
    {
        "username": "@championsleague",
        "owner": "UEFA Champions League",
        "followers": 98.6,
        "prof_act": "Club football competition",
    },
    {
        "username": "@gal_gadot",
        "owner": "Gal Gadot",
        "followers": 87.9,
        "prof_act": "Actress",
    },
    {
        "username": "@dualipa",
        "owner": "Dua Lipa",
        "followers": 87.1,
        "prof_act": "Musician",
    },
    {
        "username": "@vindiesel",
        "owner": "Vin Diesel",
        "followers": 83.1,
        "prof_act": "Actor",
    },
    {
        "username": "@nasa",
        "owner": "NASA",
        "followers": 83,
        "prof_act": "Space agency",
    },
    {
        "username": "@priyankachopra",
        "owner": "Priyanka Chopra",
        "followers": 82.5,
        "prof_act": "Actress and musician",
    },
    {
        "username": "@lalalalisa_m",
        "owner": "Lisa",
        "followers": 82.5,
        "prof_act": "Musician",
    },
    {
        "username": "@khaby00",
        "owner": "Khaby Lame",
        "followers": 80.2,
        "prof_act": "Social media personality",
    },
    {
        "username": "@snoopdogg",
        "owner": "Snoop Dogg",
        "followers": 76.6,
        "prof_act": "Musician",
    },
    {
        "username": "@shakira",
        "owner": "Shakira",
        "followers": 76.2,
        "prof_act": "Musician",
    },
    {
        "username": "@gigihadid",
        "owner": "Gigi Hadid",
        "followers": 75.8,
        "prof_act": "Model",
    },
    {
        "username": "@davidbeckham",
        "owner": "David Beckham",
        "followers": 75.4,
        "prof_act": "Footballer",
    },
    {
        "username": "@shraddhakapoor",
        "owner": "Shraddha Kapoor",
        "followers": 75,
        "prof_act": "Actress",
    },
    {
        "username": "@victoriassecret",
        "owner": "Victoria's Secret",
        "followers": 73.4,
        "prof_act": "Lingerie Company",
    },
    {
        "username": "@k.mbappe",
        "owner": "Kylian Mbappé",
        "followers": 72.6,
        "prof_act": "Footballer",
    },
    {
        "username": "@nehakakkar",
        "owner": "Neha Kakkar",
        "followers": 71.4,
        "prof_act": "Musician",
    },
]